[workspace]
members = [
    "biguint-literal",
    "blobby",
    "block-buffer",
    "block-padding",
    "collectable",
    "const-oid",
    "cpuid-bool",
    "dbl",
    "hex-literal",
    "opaque-debug",
]
